apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fried-pollack
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - toolserver-deploy.yaml
  - kagent-modelconfig.yaml
  - kagent-mcpserver.yaml
  - kagent-agent.yaml
