apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: fried-pollack-ai
    newName: dahredacrr0710a.azurecr.io/fried-pollack-ai
    newTag: 9db7585
patches:
  - target:
      kind: ServiceAccount
      name: fried-pollack-toolserver
    patch: |-
      - op: replace
        path: /metadata/annotations/azure.workload.identity~1client-id
        value: 00000000-0000-0000-0000-000000000000
